In [25]:
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [27]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [28]:
## Define the vocabulary size
voc_size=10000

In [29]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [30]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3799, 822, 1508, 2391],
 [3799, 822, 1508, 9916],
 [3799, 7251, 1508, 6715],
 [7007, 2952, 1912, 8379, 3979],
 [7007, 2952, 1912, 8379, 9433],
 [1761, 3799, 3717, 1508, 2665],
 [9012, 6286, 2149, 8379]]

In [31]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [32]:
import numpy as np

### RNN input size (sentence length) should be the same for all input sentences

In [33]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3799  822 1508 2391]
 [   0    0    0    0 3799  822 1508 9916]
 [   0    0    0    0 3799 7251 1508 6715]
 [   0    0    0 7007 2952 1912 8379 3979]
 [   0    0    0 7007 2952 1912 8379 9433]
 [   0    0    0 1761 3799 3717 1508 2665]
 [   0    0    0    0 9012 6286 2149 8379]]


In [45]:
type(embedded_docs)

numpy.ndarray

In [34]:
## feature representation
dim=10

In [35]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
# model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [36]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step


array([[[-0.04929207,  0.04713995, -0.03545159, -0.03649388,
         -0.03655433,  0.02346556,  0.02633487, -0.03075955,
         -0.02420732,  0.00289618],
        [-0.04929207,  0.04713995, -0.03545159, -0.03649388,
         -0.03655433,  0.02346556,  0.02633487, -0.03075955,
         -0.02420732,  0.00289618],
        [-0.04929207,  0.04713995, -0.03545159, -0.03649388,
         -0.03655433,  0.02346556,  0.02633487, -0.03075955,
         -0.02420732,  0.00289618],
        [-0.04929207,  0.04713995, -0.03545159, -0.03649388,
         -0.03655433,  0.02346556,  0.02633487, -0.03075955,
         -0.02420732,  0.00289618],
        [ 0.01697798, -0.04585522,  0.03245253,  0.01887004,
          0.04761392,  0.00481258,  0.01425314, -0.03105359,
         -0.0495715 ,  0.0199095 ],
        [ 0.01244996,  0.04566512,  0.00431135, -0.04670198,
         -0.02731161, -0.02522997,  0.01192684, -0.02622724,
         -0.02842664,  0.02967632],
        [-0.01971184,  0.04444918, -0.00979618,  0.0

In [39]:
embedded_docs[0]

array([   0,    0,    0,    0, 3799,  822, 1508, 2391], dtype=int32)

In [51]:
onesen = np.array([embedded_docs[0]])
onesen

array([[   0,    0,    0,    0, 3799,  822, 1508, 2391]], dtype=int32)

In [52]:
type(onesen)

numpy.ndarray

In [53]:
model.predict(onesen)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


array([[[-0.04929207,  0.04713995, -0.03545159, -0.03649388,
         -0.03655433,  0.02346556,  0.02633487, -0.03075955,
         -0.02420732,  0.00289618],
        [-0.04929207,  0.04713995, -0.03545159, -0.03649388,
         -0.03655433,  0.02346556,  0.02633487, -0.03075955,
         -0.02420732,  0.00289618],
        [-0.04929207,  0.04713995, -0.03545159, -0.03649388,
         -0.03655433,  0.02346556,  0.02633487, -0.03075955,
         -0.02420732,  0.00289618],
        [-0.04929207,  0.04713995, -0.03545159, -0.03649388,
         -0.03655433,  0.02346556,  0.02633487, -0.03075955,
         -0.02420732,  0.00289618],
        [ 0.01697798, -0.04585522,  0.03245253,  0.01887004,
          0.04761392,  0.00481258,  0.01425314, -0.03105359,
         -0.0495715 ,  0.0199095 ],
        [ 0.01244996,  0.04566512,  0.00431135, -0.04670198,
         -0.02731161, -0.02522997,  0.01192684, -0.02622724,
         -0.02842664,  0.02967632],
        [-0.01971184,  0.04444918, -0.00979618,  0.0

In [54]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[-0.04929207,  0.04713995, -0.03545159, -0.03649388, -0.03655433,
         0.02346556,  0.02633487, -0.03075955, -0.02420732,  0.00289618],
       [-0.04929207,  0.04713995, -0.03545159, -0.03649388, -0.03655433,
         0.02346556,  0.02633487, -0.03075955, -0.02420732,  0.00289618],
       [-0.04929207,  0.04713995, -0.03545159, -0.03649388, -0.03655433,
         0.02346556,  0.02633487, -0.03075955, -0.02420732,  0.00289618],
       [-0.04929207,  0.04713995, -0.03545159, -0.03649388, -0.03655433,
         0.02346556,  0.02633487, -0.03075955, -0.02420732,  0.00289618],
       [ 0.01697798, -0.04585522,  0.03245253,  0.01887004,  0.04761392,
         0.00481258,  0.01425314, -0.03105359, -0.0495715 ,  0.0199095 ],
       [ 0.01244996,  0.04566512,  0.00431135, -0.04670198, -0.02731161,
        -0.02522997,  0.01192684, -0.02622724, -0.02842664,  0.02967632],
       [-0.01971184,  0.04444918, -0.00979618,  0.03752232,  0.04186125,
        -0.01502488,  0.03289682, -0.00143693